apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarun_shori-myweb
  labels:
     app: myweb

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb

  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: tarunshori/myweb
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
